### ISSUE TITLE
Create OSO Firestarter grant profile on Karma

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#732]
## Description

The project aims to launch an Arbitrum OSS directory with auto-validation and reward mechanisms for community submissions, expand the directory to feature at least 200 prominent projects on Arbitrum across different domains with comprehensive data from both on-chain and off-chain sources, and utilize this data to propose an initial set of 4-5 "impact pools" that gauge projects' contributions to ecosystem health metrics such as new user growth, developer activity, and sequencer fees.

You can follow updates here: https://forum.arbitrum.foundation/t/open-source-observer-x-arbitrum/20266

## Direct Impacts

We believe the Arbitrum DAO, as a large and highly decentralized community, has a critical need for the infrastructure OSO provides, enabling scalable, cost-efficient grantmaking and permissionless impact evaluation. 

We provide a strong incentive for projects to open source their full code base. This, in turn, enables us and our users to observe teams’ progress and index the artifacts of their work. Moreover, by making the impact data required by the community highly visible, we make it easier for DAO governance to iterate and align funding against impact outcomes.

Unlike tools that focus solely on onchain data, OSO recognizes the contributions of developer libraries and other upstream code contributions that enable more dapps to deploy on Arbitrum. We also provide baseline data to measure Arbitrum teams against other ecosystems or types of projects.

## Long-term Impact

In the long-term, we hope that OSO can enable a higher "impact ROI" per unit of ARB invested in the ecosystem. We will offer the data to establish counterfactuals and measure grant performance over time. If the community decides to fly blind and ignore the data, then it will have no impact. If the community decides to leverage the data, then it can have significant impact, ideally improving impact ROI by at least 20% along the prioritized impact pools.

## Success Measurement

This specific grant should be measured based on (a) whether all milestones are met, and (b) the degree to which a critical number of established OSS projects in the Arbitrum ecosystem are represented on Open Source Observer.

Beyond these objectives, the grant will have been a success if OSO's proposed impact pools and other quantitative insights about ecosystem health inform the DAO’s grantmaking future decisions.

## Growth & Innovation

The grant will enable us to create an initial project registry and set of OSS metrics that the community can build on top of. Specifically, we want to engage the community to create impact metrics and evaluate grant effectiveness. We believe that better visibility on project metrics will lead to greater growth and innovation within the ecosystem, as stronger projects will get recognition and hopefully increased funding. 

## Use of Funds

The grant funds will be used to support the full-time team working on OSO (two engineers, one data/community lead), to fund community data bounties, and to cover data infrastructure costs.

## Timeframe

Around 3 months. The project began in late November / early December and is expected to wrap-up at the end of February.

**Comment by ccerv1** [comment]
## Milestone 2 progress

- [x] Inclusion of Arbitrum deployers and factory contracts for 80+ projects already on OSO ([PR](https://github.com/opensource-observer/oss-directory/pull/179/files))
- [x] Addition of 170+ OSS projects associated with Arbitrum to OSO ([PR](https://github.com/opensource-observer/oss-directory/pull/184/files))
- [ ] Linking of project deployers and GitHub orgs for new projects
- [ ] Adding all contracts deployed by projects to the OSS Directory
- [ ] Generating a final collection of 200+ well-known projects on Arbitrum
- [ ] Generating the first ecosystem coverage report for Arbitrum

**Comment by ccerv1** [comment]
Added here: https://gap.karmahq.xyz/project/open-source-observer/?tab=grants&grant=0x8cccf00cb7d540fe113b854f55077e1247088f4365600c5c852b2986204cb9b0&grant-tab=review-this-grant
